run:
  skip-files:
    - internal/handshake/cipher_suite.go
linters-settings:
  misspell:
    ignore-words:
      - ect
  depguard:
    rules:
      quicvarint:
        list-mode: strict
        files:
          - "**/github.com/quic-go/quic-go/quicvarint/*"
          - "!$test"
        allow:
          - $gostd

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - exhaustive
    - exportloopref
    - goimports
    - gofmt # redundant, since gofmt *should* be a no-op after gofumpt
    - gofumpt
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - vet

issues:
  exclude-rules:
    - path: internal/qtls
      linters:
        - depguard
