coverage:
  round: nearest
  ignore:
    - http3/gzip_reader.go
    - example/
    - interop/
    - internal/handshake/cipher_suite.go
    - internal/mocks/
    - internal/utils/linkedlist/linkedlist.go
    - internal/testdata
    - internal/synctest
    - testutils/
    - fuzzing/
    - metrics/
  status:
    project:
      default:
        threshold: 0.5
    patch: false
