coverage:
  round: nearest
  ignore:
    - http3/gzip_reader.go
    - example/
    - interop/
    - internal/handshake/cipher_suite.go
    - internal/mocks/
    - internal/utils/linkedlist/linkedlist.go
    - internal/testdata
    - testutils/
    - fuzzing/
    - metrics/
  status:
    project:
      default:
        threshold: 0.5
    patch: false

flags:
  fuzz:
    joined: false  # don't merge fuzz coverage into main coverage report
    statuses:
      - type: project
        informational: true  # don't fail a PR because of fuzz coverage
