// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package qerr

import "strconv"

const (
	_ErrorCode_name_0 = "NoErrorInternalErrorServerBusyFlowControlErrorStreamLimitErrorStreamStateErrorFinalSizeErrorFrameEncodingErrorTransportParameterErrorVersionNegotiationErrorProtocolViolation"
	_ErrorCode_name_1 = "InvalidMigration"
	_ErrorCode_name_2 = "CryptoError"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 7, 20, 30, 46, 62, 78, 92, 110, 133, 156, 173}
)

func (i ErrorCode) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case i == 12:
		return _ErrorCode_name_1
	case i == 256:
		return _ErrorCode_name_2
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
