name: Build interop Docker image

permissions: read-all

on: 
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  interop:
    runs-on: ${{ fromJSON(vars['DOCKER_RUNNER_UBUNTU'] || '"ubuntu-latest"') }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set tag name
        id: tag
        # Tagged releases won't be picked up by the interop runner automatically,
        # but they can be useful when debugging regressions.
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_OUTPUT;
          else
            echo 'tag=latest' | tee -a $GITHUB_OUTPUT;
          fi
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "."
          file: "interop/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: martenseemann/quic-go-interop:${{ steps.tag.outputs.tag }}
