name: Benchmarks

permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: codspeed-macro
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
          check-latest: true
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@3194d9a39c4d46684cb44bf7207fc56626aad8fd # v4.15.1
        with:
          mode: walltime
          run: go test -run=^$ -bench=. ./...
