name: Benchmarks

permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: codspeed-macro
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
          check-latest: true
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: walltime
          run: go test -run=^$ -bench=. ./integrationtests/self
