# Post test results as pull request comment.
#
# This is done as a separate workflow as it requires write permissions. The
# tests itself might run off of a fork, i.e. an untrusted environment and should
# thus not be granted write permissions.

name: comment-interop-results

on:
  workflow_run:
    workflows: ["run-interop-tests"]
    types:
      - completed

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Download comment-data
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          name: comment-data
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format GitHub comment
        run: |
          pwd
          ls -la
          echo '[**QUIC Interop Runner**](https://github.com/quic-interop/quic-interop-runner)' >> comment
          echo '' >> comment
          echo '```' >> comment
          cat summary >> comment
          echo '```' >> comment
          echo '' >> comment
          echo 'Download artifacts [here](' >> comment
          cat logs-url >> comment
          echo ').' >> comment
        shell: bash

      - name: Read PR Number
        id: pr-number
        run: echo "::set-output name=number::$(cat pr-number)"
        shell: bash

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment
          pr_number: ${{ steps.pr-number.outputs.number }}
