on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.x"
          check-latest: true
      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
